site_name: "Advance Robotics Course"
site_url: https://advanced_robotics.github.io
site_description: ROS Labs for the COM2009/3009 Robotics Course at The University of Sheffield (and more). 
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font: 
    text: Source Sans Pro
    code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/tuos.png
  favicon: assets/tuos_logo.svg

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  
copyright: >
  &copy; <a href="https://www.sheffield.ac.uk/engineering/diamond-engineering/our-staff/tom-howard">Tom Howard</a>, The University of Sheffield, 2024 (License: <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC</a>)<br />
  <a href="#__consent">Change cookie settings</a>
repo_url: https://github.com/jmgandarias/advanced_robotics.github.io
repo_name: jmgandarias/advanced_robotics.github.io
edit_uri: ./edit/main/docs

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      enabled: !ENV [CI, false]
  - privacy:
      enabled: !ENV [CI, false]
  - redirects:
      redirect_maps:
        "com2009/la1/README.md": "com2009/assignment1/README.md"
        "com2009/la1/week1.md": "com2009/assignment1/part1.md"
        "com2009/la1/week2.md": "com2009/assignment1/part2.md"
        "com2009/la1/week3.md": "com2009/assignment1/part3.md"
        "com2009/la1/week4.md": "com2009/assignment1/part4.md"
        "com2009/la1/week5.md": "com2009/assignment1/part5.md"
        "com2009/la1/week6.md": "com2009/assignment1/part6.md"
        "com2009/la2/README.md": "com2009/assignment2/README.md"
        "com2009/la2/getting-started.md": "com2009/assignment2/getting-started.md"
        "com2009/la2/overview.md": "com2009/assignment2/README.md"
        "com2009/la2/task1.md": "com2009/assignment2/parta/task1.md"
        "com2009/la2/task2.md": "com2009/assignment2/parta/task2.md"
        "com2009/la2/task3.md": "com2009/assignment2/README.md"
        "com2009/la2/task4.md": "com2009/assignment2/README.md"
        "com2009/la2/task5.md": "com2009/assignment2/README.md"
        "com2009/la2/extras/laptops.md": "waffles/tips/laptops.md"
        "com2009/la2/extras/submission.md": "com2009/assignment2/submission.md"
        "com2009/la2/extras/README.md": "com2009/assignment2/README.md"
        "wsl-ros/README.md": "software/wsl-ros/install.md"
        "wsl-ros/backup-restore.md": "software/on-campus/getting-started.md"
        "wsl-ros/configure-vscode.md": "software/on-campus/vscode.md"
        "wsl-ros/vscode.md": "software/on-campus/vscode.md"
        "wsl-ros/first-run.md": "software/on-campus/getting-started.md"
        "wsl-ros/wsl-ros-return.md": "software/on-campus/getting-started.md"
        "wsl-ros/rdp.md": "software/on-campus/rdp.md"
        "wsl-ros/wt-settings.md": "software/README.md"
        "wsl-ros/linux-term.md": "software/on-campus/linux-term.md"
        "wsl-ros/installing.md": "software/README.md"       

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-1SSCKMNFPR
  consent:
    title: Cookie consent
    description: 
      We use cookies to monitor the usage of these resources, and to understand 
      how effective they are in supporting your learning. Cookies also help us to 
      evaluate how much impact our teaching materials are making in the community.
      With your support, you are helping us to make our teaching resources better.
